collections:
  authors:
    output: true

baseurl: "/digital-legacy"

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

sass:
  sass_dir: ./_sass

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  